import { Game, Review, User, Listing, NewsArticle } from "./types";

export const GAMES: Game[] = [
  {
    id: "1",
    slug: "god-of-war-ragnarok",
    title: "God of War: Ragnarök",
    cover: "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png",
    trailer: "https://www.youtube.com/embed/EE-4GvjKcfs",
    gallery: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/library_hero.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/header.jpg",
    ],
    description: "God of War Ragnarök é um jogo de ação e aventura desenvolvido pela Santa Monica Studio e publicado pela Sony Interactive Entertainment.",
    synopsis: "Kratos e Atreus devem viajar pelos Nove Reinos e preparar-se para as batalhas que mudarão o mundo para sempre — o Ragnarök.",
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    engine: "Proprietary",
    releaseDate: "2022-11-09",
    suggestedPrice: 349.90,
    platforms: ["PS5", "PS4"],
    genres: ["Ação", "Aventura", "Hack and Slash"],
    avgPlayTime: "25-35 horas",
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Português (BR)", "Inglês", "Espanhol"],
    subtitles: ["Português (BR)", "Inglês", "Espanhol", "Francês"],
    dubbing: ["Inglês", "Japonês"],
    ageRating: "16+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 94,
    openCriticScore: 94,
    userScore: 9.2,
    adminScore: 9.5,
    siteScores: [
      { site: "IGN", score: 10 },
      { site: "Metacritic", score: 94 },
      { site: "OpenCritic", score: 94 },
      { site: "GameSpot", score: 10 },
      { site: "Eurogamer", score: 100 },
      { site: "Push Square", score: 10 },
      { site: "GamesRadar", score: 90 },
    ],
    worldAvg: 9.5,
    featured: true,
    tags: ["exclusivo", "premiado", "single-player"],
  },
  {
    id: "2",
    slug: "spider-man-2",
    title: "Marvel's Spider-Man 2",
    cover: "https://upload.wikimedia.org/wikipedia/en/0/0f/SpiderMan2PS5BoxArt.jpeg",
    trailer: "https://www.youtube.com/embed/S1Ro0L4qEU4",
    gallery: [],
    description: "Marvel's Spider-Man 2 é o terceiro jogo principal da série de videogames Spider-Man da Insomniac Games.",
    synopsis: "Peter Parker e Miles Morales voltam para mais uma aventura, dessa vez enfrentando Venom e o Caçador Kraven.",
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2023-10-20",
    suggestedPrice: 349.90,
    platforms: ["PS5"],
    genres: ["Ação", "Aventura", "Open World"],
    avgPlayTime: "18-25 horas",
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Português (BR)", "Inglês", "Espanhol"],
    subtitles: ["Português (BR)", "Inglês", "Espanhol"],
    dubbing: ["Inglês"],
    ageRating: "16+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 90,
    openCriticScore: 91,
    userScore: 8.9,
    adminScore: 9.0,
    siteScores: [
      { site: "IGN", score: 9 },
      { site: "Metacritic", score: 90 },
      { site: "OpenCritic", score: 91 },
      { site: "GameSpot", score: 90 },
      { site: "Push Square", score: 90 },
    ],
    worldAvg: 9.0,
    featured: true,
    tags: ["exclusivo", "marvel", "open-world"],
  },
  {
    id: "3",
    slug: "final-fantasy-xvi",
    title: "Final Fantasy XVI",
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/2515020/library_600x900.jpg",
    trailer: "https://www.youtube.com/embed/rPBi3cyEuuI",
    gallery: [],
    description: "Final Fantasy XVI é um RPG de ação desenvolvido e publicado pela Square Enix.",
    synopsis: "No mundo de Valisthea, dominado pelos Cristais Éter, um jovem chamado Clive Rosfield parte em uma missão de vingança que se tornará a jornada que vai moldar o destino do mundo.",
    developer: "Square Enix",
    publisher: "Square Enix",
    releaseDate: "2023-06-22",
    suggestedPrice: 299.90,
    platforms: ["PS5"],
    genres: ["RPG", "Ação", "JRPG"],
    avgPlayTime: "35-50 horas",
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Inglês", "Japonês"],
    subtitles: ["Português (BR)", "Inglês", "Japonês"],
    dubbing: ["Inglês", "Japonês"],
    ageRating: "18+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 87,
    openCriticScore: 87,
    userScore: 8.6,
    adminScore: 8.8,
    siteScores: [
      { site: "IGN", score: 9 },
      { site: "Metacritic", score: 87 },
      { site: "OpenCritic", score: 87 },
      { site: "GameSpot", score: 80 },
    ],
    worldAvg: 8.7,
    featured: true,
    tags: ["rpg", "jrpg", "magia"],
  },
  {
    id: "4",
    slug: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_600x900.jpg",
    trailer: "https://www.youtube.com/embed/wLfZL4E1kKY",
    gallery: [],
    description: "Baldur's Gate 3 é um RPG desenvolvido e publicado pela Larian Studios.",
    synopsis: "Reúna seus aliados e avance ao Baldur's Gate, uma cidade assolada por escuridão e corrupção. Você deve tomar decisões morais difíceis que moldará o mundo ao seu redor.",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    releaseDate: "2023-12-06",
    suggestedPrice: 299.90,
    platforms: ["PS5", "PC"],
    genres: ["RPG", "Estratégia", "Coop"],
    avgPlayTime: "80-200 horas",
    online: true,
    offline: true,
    maxPlayers: 4,
    languages: ["Inglês", "Espanhol"],
    subtitles: ["Português (BR)", "Inglês", "Espanhol"],
    dubbing: ["Inglês"],
    ageRating: "18+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 97,
    openCriticScore: 96,
    userScore: 9.5,
    adminScore: 9.8,
    siteScores: [
      { site: "IGN", score: 10 },
      { site: "Metacritic", score: 97 },
      { site: "OpenCritic", score: 96 },
      { site: "GameSpot", score: 100 },
      { site: "Eurogamer", score: 100 },
    ],
    worldAvg: 9.7,
    featured: true,
    tags: ["rpg", "coop", "goty-2023"],
  },
  {
    id: "5",
    slug: "hogwarts-legacy",
    title: "Hogwarts Legacy",
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/990080/library_600x900.jpg",
    trailer: "https://www.youtube.com/embed/3EF_dF57mBI",
    gallery: [],
    description: "Hogwarts Legacy é um RPG de ação de mundo aberto desenvolvido pela Avalanche Software.",
    synopsis: "Viva a experiência de ser um estudante de Hogwarts no século XIX, explore locais familiares e novos, e seja responsável por uma descoberta mágica perigosa.",
    developer: "Avalanche Software",
    publisher: "Warner Bros. Games",
    releaseDate: "2023-02-10",
    suggestedPrice: 249.90,
    platforms: ["PS5", "PS4", "Xbox", "PC"],
    genres: ["RPG", "Aventura", "Open World"],
    avgPlayTime: "30-60 horas",
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Inglês", "Espanhol"],
    subtitles: ["Português (BR)", "Inglês", "Espanhol"],
    dubbing: ["Inglês"],
    ageRating: "12+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 84,
    openCriticScore: 84,
    userScore: 8.8,
    adminScore: 8.5,
    siteScores: [
      { site: "IGN", score: 85 },
      { site: "Metacritic", score: 84 },
      { site: "OpenCritic", score: 84 },
    ],
    worldAvg: 8.4,
    featured: false,
    tags: ["harry-potter", "magia", "open-world"],
  },
  {
    id: "6",
    slug: "alan-wake-2",
    title: "Alan Wake 2",
    cover: "https://upload.wikimedia.org/wikipedia/en/e/ed/Alan_Wake_2_box_art.jpg",
    trailer: "https://www.youtube.com/embed/XZ_Ks0r2p3Q",
    gallery: [],
    description: "Alan Wake 2 é um jogo de survival horror desenvolvido pela Remedy Entertainment.",
    synopsis: "Saga Anderson investiga uma série de assassinatos rituais enquanto Alan Wake, preso em um mundo de pesadelo, escreve uma história de terror.",
    developer: "Remedy Entertainment",
    publisher: "Epic Games Publishing",
    releaseDate: "2023-10-27",
    suggestedPrice: 249.90,
    platforms: ["PS5", "Xbox Series", "PC"],
    genres: ["Terror", "Survival Horror", "Aventura"],
    avgPlayTime: "15-20 horas",
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Inglês"],
    subtitles: ["Português (BR)", "Inglês"],
    dubbing: ["Inglês"],
    ageRating: "18+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 89,
    openCriticScore: 89,
    userScore: 8.8,
    adminScore: 9.0,
    siteScores: [
      { site: "IGN", score: 90 },
      { site: "Metacritic", score: 89 },
      { site: "OpenCritic", score: 89 },
      { site: "GameSpot", score: 90 },
    ],
    worldAvg: 8.9,
    featured: false,
    tags: ["terror", "narrativa", "atmosférico"],
  },
];

export const REVIEWS: Review[] = [
  {
    id: "1",
    gameId: "1",
    title: "God of War Ragnarök — Uma Obra-Prima Épica",
    text: `God of War Ragnarök eleva ainda mais a fasquia estabelecida pelo seu predecessor de 2018. A Santa Monica Studio entregou não apenas uma sequência, mas uma experiência cinematográfica de dar inveja a qualquer produção de Hollywood.

A relação entre Kratos e Atreus continua sendo o coração pulsante do jogo. Vemos o crescimento de Atreus de um adolescente impulsivo para um jovem que começa a entender seu papel no mundo — e a tensão entre pai e filho nunca pareceu tão autêntica e emocionante.

O combate foi ampliado de forma magistral. Além do Leviatã e das Lâminas do Caos, ganhos de novos poderes e habilidades que mantêm as batalhas frescas do início ao fim. Os inimigos são diversificados e desafiadores, exigindo estratégia e adaptação constante.

Os Nove Reinos estão absolutamente deslumbrantes. Cada área tem uma identidade visual própria, e explorar todos eles é uma das maiores alegrias que um jogador pode ter. Svartalfheim, em particular, é uma obra de arte em design de mundo.`,
    pros: [
      "História emocionante e bem escrita",
      "Combate refinado e satisfatório",
      "Mundos deslumbrantes para explorar",
      "Personagens bem desenvolvidos",
      "Trilha sonora épica",
      "Excelente performance no PS5",
    ],
    cons: [
      "Alguns puzzles podem ser repetitivos",
      "O ritmo da história cai levemente no meio",
      "Boss fights nem sempre estão no nível do 2018",
    ],
    conclusion: "God of War Ragnarök é uma das melhores exclusividades do PlayStation e um dos melhores jogos da geração. Imperdível.",
    scores: {
      graphics: 10,
      gameplay: 9.5,
      fun: 10,
      story: 10,
      soundtrack: 9.5,
      performance: 9.5,
      replay: 8.5,
      multiplayer: 0,
      difficulty: 8.5,
      visual: 10,
      ai: 8.5,
      optimization: 9.5,
      content: 9.5,
    },
    overallScore: 9.5,
    author: "Redação Upa que Passa",
    publishedAt: "2022-11-15",
    likes: 342,
  },
];

export const USERS: User[] = [
  {
    id: "1",
    nickname: "KratosFan_BR",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=KratosFan",
    bio: "Gamer de carteirinha. Platinador compulsivo.",
    favoriteGames: ["1", "2", "4"],
    console: "PS5",
    city: "São Paulo",
    state: "SP",
    socialLinks: [
      { platform: "twitch", url: "#" },
      { platform: "youtube", url: "#" },
    ],
    reviewsCount: 47,
    commentsCount: 284,
    tradesCount: 23,
    reputation: 98,
    level: 42,
    achievements: [
      { id: "1", name: "Platinador", description: "Conquistou 10 platinas", icon: "🏆" },
      { id: "2", name: "Crítico", description: "Escreveu 50 reviews", icon: "✍️" },
      { id: "3", name: "Negociante", description: "Realizou 20 trocas", icon: "🤝" },
    ],
    joinedAt: "2021-03-15",
  },
  {
    id: "2",
    nickname: "SpiderMilena",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SpiderMilena",
    bio: "Fã da Marvel e de JRPGs. Sempre procurando o próximo platinão.",
    favoriteGames: ["2", "3"],
    console: "PS5",
    city: "Rio de Janeiro",
    state: "RJ",
    socialLinks: [],
    reviewsCount: 12,
    commentsCount: 89,
    tradesCount: 7,
    reputation: 94,
    level: 18,
    achievements: [
      { id: "1", name: "Iniciante", description: "Fez seu primeiro review", icon: "⭐" },
    ],
    joinedAt: "2023-06-20",
  },
];

export const LISTINGS: Listing[] = [
  {
    id: "1",
    userId: "1",
    userNickname: "KratosFan_BR",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=KratosFan",
    userReputation: 98,
    photos: ["https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png"],
    title: "God of War Ragnarök - Lacrado",
    description: "Jogo lacrado, comprado na pré-venda, nunca aberto. Migrei para o digital.",
    price: 199.90,
    condition: "lacrado",
    media: "fisica",
    city: "São Paulo",
    state: "SP",
    shipping: true,
    pickup: true,
    acceptsTrade: true,
    paymentMethods: ["pix", "dinheiro"],
    category: "Ação",
    gameId: "1",
    createdAt: "2024-01-15",
    views: 234,
    favorites: 18,
    active: true,
    wantedGames: ["Spider-Man 2", "Baldur's Gate 3"],
  },
  {
    id: "2",
    userId: "2",
    userNickname: "SpiderMilena",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SpiderMilena",
    userReputation: 94,
    photos: ["https://upload.wikimedia.org/wikipedia/en/0/0f/SpiderMan2PS5BoxArt.jpeg"],
    title: "Spider-Man 2 - Usado - Bom Estado",
    description: "Jogo em bom estado, poucas arranhadas na capa. Zerado, todos os troféus coletados.",
    price: 159.90,
    condition: "bom estado",
    media: "fisica",
    city: "Rio de Janeiro",
    state: "RJ",
    shipping: true,
    pickup: false,
    acceptsTrade: false,
    paymentMethods: ["pix", "cartao"],
    category: "Ação",
    gameId: "2",
    createdAt: "2024-01-20",
    views: 145,
    favorites: 9,
    active: true,
  },
  {
    id: "3",
    userId: "1",
    userNickname: "KratosFan_BR",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=KratosFan",
    userReputation: 98,
    photos: ["https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_600x900.jpg"],
    title: "Baldur's Gate 3 - Troca!",
    description: "Tenho BG3 e procuro trocar por Final Fantasy XVI + diferença. Jogo em ótimo estado.",
    price: 280.00,
    condition: "como novo",
    media: "fisica",
    city: "São Paulo",
    state: "SP",
    shipping: true,
    pickup: true,
    acceptsTrade: true,
    paymentMethods: ["pix"],
    category: "RPG",
    gameId: "4",
    createdAt: "2024-01-25",
    views: 89,
    favorites: 4,
    active: true,
    wantedGames: ["Final Fantasy XVI"],
  },
];

export const NEWS: NewsArticle[] = [
  {
    id: "1",
    slug: "ps5-pro-lancamento-brasil",
    title: "PS5 Pro chega ao Brasil com preço oficial de R$ 4.999",
    excerpt: "Sony anuncia o PS5 Pro para o mercado brasileiro com GPU aprimorada e suporte a 8K.",
    content: "A Sony Interactive Entertainment anunciou oficialmente o PlayStation 5 Pro para o mercado brasileiro...",
    cover: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Video_%C3%BCber_die_PS5_Pro_%28BeatEmUps%29_%282160p_60fps_VP9-128kbit_AAC%29-00.02.23.200.png",
    author: "Redação UQP",
    publishedAt: "2024-09-10",
    category: "Hardware",
    tags: ["PS5", "PS5 Pro", "Sony", "Hardware"],
    views: 12450,
    likes: 342,
  },
  {
    id: "2",
    slug: "gta-6-data-lancamento-confirmada",
    title: "GTA 6: Data de lançamento no PS5 confirmada para 2025",
    excerpt: "Rockstar Games confirma que GTA VI chegará em maio de 2025 para PlayStation 5 e Xbox Series.",
    content: "A Rockstar Games confirmou que Grand Theft Auto VI terá lançamento em maio de 2025...",
    cover: "https://upload.wikimedia.org/wikipedia/en/4/46/Grand_Theft_Auto_VI.png",
    author: "Redação UQP",
    publishedAt: "2024-01-08",
    category: "Notícias",
    tags: ["GTA 6", "Rockstar", "PS5", "Lançamento"],
    views: 45200,
    likes: 1203,
  },
  {
    id: "3",
    slug: "state-of-play-resumo",
    title: "State of Play: Todos os anúncios do evento da Sony",
    excerpt: "Confira todos os jogos e novidades anunciadas no State of Play de Janeiro de 2024.",
    content: "O State of Play de Janeiro trouxe diversas novidades para os donos de PlayStation 5...",
    cover: "https://upload.wikimedia.org/wikipedia/commons/7/77/Black_and_white_Playstation_5_base_edition_with_controller.png",
    author: "Redação UQP",
    publishedAt: "2024-01-31",
    category: "Eventos",
    tags: ["State of Play", "Sony", "PS5", "Anúncios"],
    views: 23100,
    likes: 678,
  },
];

export function getScoreColor(score: number): string {
  if (score >= 9) return "text-green-400";
  if (score >= 7.5) return "text-lime-400";
  if (score >= 6) return "text-yellow-400";
  if (score >= 4) return "text-orange-400";
  return "text-red-400";
}

export function getScoreBg(score: number): string {
  if (score >= 9) return "bg-green-400";
  if (score >= 7.5) return "bg-lime-400";
  if (score >= 6) return "bg-yellow-400";
  if (score >= 4) return "bg-orange-400";
  return "bg-red-400";
}

export function formatScore(score: number): string {
  return score % 1 === 0 ? score.toString() : score.toFixed(1);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(price);
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("pt-BR");
}
