import { Game, Review, User, Listing, NewsArticle } from "./types";

export const GAMES: Game[] = [
  {
    id: "1",
    slug: "god-of-war-ragnarok",
    title: "God of War: Ragnarök",
    cover: "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png",
    trailer: "https://www.youtube.com/embed/EE-4GvjKcfs",
    gallery: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/library_hero.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/header.jpg",
    ],
    description: "God of War Ragnarök é um jogo de ação e aventura desenvolvido pela Santa Monica Studio e publicado pela Sony Interactive Entertainment.",
    synopsis: "Kratos e Atreus devem viajar pelos Nove Reinos e preparar-se para as batalhas que mudarão o mundo para sempre — o Ragnarök.",
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    engine: "Proprietary",
    releaseDate: "2022-11-09",
    suggestedPrice: 349.90,
    platforms: ["PS5", "PS4"],
    genres: ["Ação", "Aventura", "Hack and Slash"],
    avgPlayTime: "25-35 horas",
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Português (BR)", "Inglês", "Espanhol"],
    subtitles: ["Português (BR)", "Inglês", "Espanhol", "Francês"],
    dubbing: ["Inglês", "Japonês"],
    ageRating: "16+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 94,
    openCriticScore: 92,
    userScore: 8.3,
    adminScore: 9.5,
    siteScores: [
      { site: "IGN", score: 10 },
      { site: "Metacritic", score: 94 },
      { site: "OpenCritic", score: 92 },
      { site: "GameSpot", score: 9 },
      { site: "Push Square", score: 10 },
      { site: "GamesRadar", score: 90 },
    ],
    worldAvg: 9.4,
    featured: true,
    tags: ["exclusivo", "premiado", "single-player"],
  },
  {
    id: "2",
    slug: "spider-man-2",
    title: "Marvel's Spider-Man 2",
    cover: "https://upload.wikimedia.org/wikipedia/en/0/0f/SpiderMan2PS5BoxArt.jpeg",
    trailer: "https://www.youtube.com/embed/S1Ro0L4qEU4",
    gallery: [],
    description: "Marvel's Spider-Man 2 é o terceiro jogo principal da série de videogames Spider-Man da Insomniac Games.",
    synopsis: "Peter Parker e Miles Morales voltam para mais uma aventura, dessa vez enfrentando Venom e o Caçador Kraven.",
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2023-10-20",
    suggestedPrice: 349.90,
    platforms: ["PS5"],
    genres: ["Ação", "Aventura", "Open World"],
    avgPlayTime: "18-25 horas",
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Português (BR)", "Inglês", "Espanhol"],
    subtitles: ["Português (BR)", "Inglês", "Espanhol"],
    dubbing: ["Inglês"],
    ageRating: "16+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 90,
    openCriticScore: 88,
    userScore: 8.6,
    adminScore: 9.0,
    siteScores: [
      { site: "IGN", score: 8 },
      { site: "Metacritic", score: 90 },
      { site: "OpenCritic", score: 88 },
      { site: "GameSpot", score: 8 },
      { site: "Push Square", score: 8 },
    ],
    worldAvg: 8.4,
    featured: true,
    tags: ["exclusivo", "marvel", "open-world"],
  },
  {
    id: "3",
    slug: "final-fantasy-xvi",
    title: "Final Fantasy XVI",
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/2515020/library_600x900.jpg",
    trailer: "https://www.youtube.com/embed/rPBi3cyEuuI",
    gallery: [],
    description: "Final Fantasy XVI é um RPG de ação desenvolvido e publicado pela Square Enix.",
    synopsis: "No mundo de Valisthea, dominado pelos Cristais Éter, um jovem chamado Clive Rosfield parte em uma missão de vingança que se tornará a jornada que vai moldar o destino do mundo.",
    developer: "Square Enix",
    publisher: "Square Enix",
    releaseDate: "2023-06-22",
    suggestedPrice: 299.90,
    platforms: ["PS5"],
    genres: ["RPG", "Ação", "JRPG"],
    avgPlayTime: "35-50 horas",
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Inglês", "Japonês"],
    subtitles: ["Português (BR)", "Inglês", "Japonês"],
    dubbing: ["Inglês", "Japonês"],
    ageRating: "18+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 87,
    openCriticScore: 87,
    userScore: 8.4,
    adminScore: 8.8,
    siteScores: [
      { site: "IGN", score: 9 },
      { site: "Metacritic", score: 87 },
      { site: "OpenCritic", score: 87 },
      { site: "GameSpot", score: 9 },
    ],
    worldAvg: 8.9,
    featured: true,
    tags: ["rpg", "jrpg", "magia"],
  },
  {
    id: "4",
    slug: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_600x900.jpg",
    trailer: "https://www.youtube.com/embed/wLfZL4E1kKY",
    gallery: [],
    description: "Baldur's Gate 3 é um RPG desenvolvido e publicado pela Larian Studios.",
    synopsis: "Reúna seus aliados e avance ao Baldur's Gate, uma cidade assolada por escuridão e corrupção. Você deve tomar decisões morais difíceis que moldará o mundo ao seu redor.",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    releaseDate: "2023-12-06",
    suggestedPrice: 299.90,
    platforms: ["PS5", "PC"],
    genres: ["RPG", "Estratégia", "Coop"],
    avgPlayTime: "80-200 horas",
    online: true,
    offline: true,
    maxPlayers: 4,
    languages: ["Inglês", "Espanhol"],
    subtitles: ["Português (BR)", "Inglês", "Espanhol"],
    dubbing: ["Inglês"],
    ageRating: "18+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 96,
    openCriticScore: 96,
    userScore: 8.7,
    adminScore: 9.4,
    siteScores: [
      { site: "IGN", score: 10 },
      { site: "Metacritic", score: 96 },
      { site: "OpenCritic", score: 96 },
      { site: "GameSpot", score: 100 },
      { site: "Eurogamer", score: 80 },
    ],
    worldAvg: 9.4,
    featured: true,
    tags: ["rpg", "coop", "goty-2023"],
  },
  {
    id: "5",
    slug: "hogwarts-legacy",
    title: "Hogwarts Legacy",
    cover: "https://cdn.cloudflare.steamstatic.com/steam/apps/990080/library_600x900.jpg",
    trailer: "https://www.youtube.com/embed/3EF_dF57mBI",
    gallery: [],
    description: "Hogwarts Legacy é um RPG de ação de mundo aberto desenvolvido pela Avalanche Software.",
    synopsis: "Viva a experiência de ser um estudante de Hogwarts no século XIX, explore locais familiares e novos, e seja responsável por uma descoberta mágica perigosa.",
    developer: "Avalanche Software",
    publisher: "Warner Bros. Games",
    releaseDate: "2023-02-10",
    suggestedPrice: 249.90,
    platforms: ["PS5", "PS4", "Xbox", "PC"],
    genres: ["RPG", "Aventura", "Open World"],
    avgPlayTime: "30-60 horas",
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Inglês", "Espanhol"],
    subtitles: ["Português (BR)", "Inglês", "Espanhol"],
    dubbing: ["Inglês"],
    ageRating: "12+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 84,
    openCriticScore: 84,
    userScore: 8.1,
    adminScore: 8.5,
    siteScores: [
      { site: "IGN", score: 9 },
      { site: "Metacritic", score: 84 },
      { site: "OpenCritic", score: 84 },
    ],
    worldAvg: 8.6,
    featured: false,
    tags: ["harry-potter", "magia", "open-world"],
  },
  {
    id: "6",
    slug: "alan-wake-2",
    title: "Alan Wake 2",
    cover: "https://upload.wikimedia.org/wikipedia/en/e/ed/Alan_Wake_2_box_art.jpg",
    trailer: "https://www.youtube.com/embed/XZ_Ks0r2p3Q",
    gallery: [],
    description: "Alan Wake 2 é um jogo de survival horror desenvolvido pela Remedy Entertainment.",
    synopsis: "Saga Anderson investiga uma série de assassinatos rituais enquanto Alan Wake, preso em um mundo de pesadelo, escreve uma história de terror.",
    developer: "Remedy Entertainment",
    publisher: "Epic Games Publishing",
    releaseDate: "2023-10-27",
    suggestedPrice: 249.90,
    platforms: ["PS5", "Xbox Series", "PC"],
    genres: ["Terror", "Survival Horror", "Aventura"],
    avgPlayTime: "15-20 horas",
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Inglês"],
    subtitles: ["Português (BR)", "Inglês"],
    dubbing: ["Inglês"],
    ageRating: "18+",
    links: [{ label: "Site Oficial", url: "#" }],
    metacriticScore: 89,
    openCriticScore: 89,
    userScore: 8.5,
    adminScore: 9.0,
    siteScores: [
      { site: "IGN", score: 90 },
      { site: "Metacritic", score: 89 },
      { site: "OpenCritic", score: 89 },
      { site: "GameSpot", score: 100 },
    ],
    worldAvg: 9.2,
    featured: false,
    tags: ["terror", "narrativa", "atmosférico"],
  },
  {
    id: "7",
    slug: "dune-awakening",
    title: "Dune: Awakening",
    cover: "https://media.rawg.io/media/games/593/593c074cdf1ea15b8c9a2513676020e6.jpg",
    gallery: [
      "https://media.rawg.io/media/screenshots/e87/e8772839436dd66bebeef5eb69398539.jpg",
      "https://media.rawg.io/media/screenshots/add/add325dc8cc03cc370aaaf5c7dd126f6.jpg",
    ],
    description: "Dune: Awakening é um jogo de sobrevivência em mundo aberto ambientado no planeta Arrakis, desenvolvido e publicado pela Funcom com o motor Unreal Engine 5.",
    synopsis: "Escolhido pela Bene Gesserit para investigar o desaparecimento dos Fremen, o jogador precisa sobreviver ao clima hostil de Arrakis, escapar dos vermes-de-areia, disputar a política do Landsraad e construir sua própria base no deserto. O jogo chegou ao PC em 10/06/2025 — as notas de crítica desta ficha são inteiramente da versão PC, já que o PS5 ainda não recebeu o jogo. A versão para PlayStation 5 chega em 22/09/2026 com um modo single-player inédito, criado especialmente para consoles, ausente na versão de PC (que é exclusivamente multiplayer).",
    developer: "Funcom",
    publisher: "Funcom",
    engine: "Unreal Engine 5",
    releaseDate: "2026-09-22",
    suggestedPrice: 179.00,
    platforms: ["PS5", "PC", "Xbox Series X|S"],
    genres: ["Ação", "Aventura", "RPG", "MMO"],
    online: true,
    offline: true,
    maxPlayers: 1,
    languages: ["Inglês", "Francês", "Italiano", "Alemão", "Espanhol", "Japonês", "Coreano", "Polonês", "Português (BR)", "Russo", "Chinês Simplificado", "Chinês Tradicional", "Turco", "Ucraniano"],
    subtitles: ["Inglês", "Francês", "Italiano", "Alemão", "Espanhol", "Japonês", "Coreano", "Polonês", "Português (BR)", "Russo", "Chinês Simplificado", "Chinês Tradicional", "Turco", "Ucraniano"],
    dubbing: ["Inglês"],
    ageRating: "18+",
    links: [
      { label: "Steam", url: "https://store.steampowered.com/app/1172710/Dune_Awakening/" },
      { label: "Anúncio PS5 - PlayStation Blog", url: "https://blog.playstation.com/2026/07/02/what-dune-awakening-brings-to-playstation-5-sept-22/" },
    ],
    metacriticScore: 78,
    openCriticScore: 81,
    userScore: 6.1,
    siteScores: [
      { site: "IGN", score: 8, url: "https://www.ign.com/articles/dune-awakening-review" },
      { site: "GameSpot", score: 7, url: "https://www.gamespot.com/reviews/dune-awakening-review/1900-6418381/" },
      { site: "Eurogamer", score: 8, url: "https://www.eurogamer.net/dune-awakening-review" },
      { site: "PC Gamer", score: 8, url: "https://www.pcgamer.com/games/mmo/dune-awakening-review/" },
    ],
    worldAvg: 7.8,
    tags: ["Nota provisória (versão PC)", "sobrevivência", "mundo-aberto", "mmo", "ficção-científica"],
  },
  {
    id: "8",
    slug: "astro-bot",
    title: "Astro Bot",
    cover: "https://media.rawg.io/media/games/b19/b19cdd6be95ffffd63fdd2d1fbac057a.jpg",
    gallery: [],
    description: "Astro Bot é um jogo de plataforma e ação desenvolvido pela Team Asobi e publicado pela Sony Interactive Entertainment, exclusivo para PS5, lançado em setembro de 2024 para celebrar os 30 anos da marca PlayStation.",
    synopsis: "Quando o maior e mais antigo inimigo galáctico de Astro ataca a nave-mãe PS5, espalhando a tripulação pelo espaço sideral, Astro é o único capaz de resolver o problema. Em uma missão por mais de 50 planetas, o jogador resgata robôs perdidos — muitos deles fantasiados de ícones clássicos do PlayStation — e reconstrói a nave-mãe usando novos poderes como socos elásticos, foguetes e uma esponja gigante, tudo sentido através dos recursos do controle DualSense.",
    developer: "Team Asobi",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2024-09-06",
    suggestedPrice: 339.90,
    platforms: ["PS5"],
    genres: ["Ação", "Plataforma"],
    online: false,
    offline: true,
    maxPlayers: 1,
    languages: ["Alemão", "Chinês Simplificado", "Chinês Tradicional", "Coreano", "Dinamarquês", "Espanhol", "Espanhol (México)", "Finlandês", "Francês (Canadá)", "Francês (França)", "Grego", "Holandês", "Húngaro", "Inglês", "Italiano", "Japonês", "Norueguês", "Polonês", "Português (BR)", "Português (Portugal)", "Romeno", "Russo", "Sueco", "Tailandês", "Tcheco", "Turco", "Ucraniano", "Vietnamita", "Árabe"],
    subtitles: ["Alemão", "Chinês Simplificado", "Chinês Tradicional", "Coreano", "Dinamarquês", "Espanhol", "Espanhol (México)", "Finlandês", "Francês (Canadá)", "Francês (França)", "Grego", "Holandês", "Húngaro", "Inglês", "Italiano", "Japonês", "Norueguês", "Polonês", "Português (BR)", "Português (Portugal)", "Romeno", "Russo", "Sueco", "Tailandês", "Tcheco", "Turco", "Ucraniano", "Vietnamita", "Árabe"],
    dubbing: [],
    ageRating: "Livre",
    links: [{ label: "PS Store", url: "https://store.playstation.com/pt-br/product/UP9000-PPSA21564_00-0000000000000000" }],
    metacriticScore: 94,
    openCriticScore: 94,
    userScore: 9.0,
    siteScores: [
      { site: "IGN", score: 9, url: "https://opencritic.com/game/17118/astro-bot" },
      { site: "GameSpot", score: 9, url: "https://www.gamespot.com/reviews/astro-bot-review-fly-me-to-the-moon/1900-6418277/" },
      { site: "Eurogamer", score: 10, url: "https://opencritic.com/game/17118/astro-bot" },
      { site: "Push Square", score: 10, url: "https://www.pushsquare.com/reviews/ps5/astro-bot" },
    ],
    worldAvg: 9.5,
    tags: ["exclusivo", "plataforma", "single-player"],
  },
  {
    id: "9",
    slug: "death-stranding-2",
    title: "Death Stranding 2: On the Beach",
    cover: "https://media.rawg.io/media/games/b85/b85bc300d42588af66fb516b7563f74f.jpg",
    gallery: [
      "https://media.rawg.io/media/screenshots/7a9/7a97a649fde5f258651ae5e69abf0ed0.jpg",
      "https://media.rawg.io/media/screenshots/372/372b0916c1ce240a4406373c120abd8f.jpg",
      "https://media.rawg.io/media/screenshots/9c4/9c4d0e73de232433f8b977c39ca65d45.jpg",
    ],
    description: "Death Stranding 2: On the Beach é um jogo de ação e aventura desenvolvido pela Kojima Productions e publicado pela Sony Interactive Entertainment, com o motor Decima.",
    synopsis: "Onze meses após os eventos do primeiro Death Stranding, Sam Porter Bridges e seus companheiros partem em uma nova jornada para conectar a Austrália à Rede Quiral e salvar a humanidade da extinção, enfrentando inimigos sobrenaturais, desastres naturais e a misteriosa chuva Timefall — enquanto o jogo questiona se realmente deveríamos ter nos conectado.",
    developer: "Kojima Productions",
    publisher: "Sony Interactive Entertainment",
    engine: "Decima",
    releaseDate: "2025-06-26",
    suggestedPrice: 399.90,
    platforms: ["PS5", "PC"],
    genres: ["Ação", "Aventura"],
    online: true,
    offline: true,
    maxPlayers: 1,
    languages: ["Inglês", "Francês", "Italiano", "Alemão", "Espanhol", "Árabe", "Tcheco", "Holandês", "Grego", "Japonês", "Coreano", "Polonês", "Português (BR)", "Português (Portugal)", "Russo", "Chinês Simplificado", "Espanhol (América Latina)", "Chinês Tradicional"],
    subtitles: ["Inglês", "Francês", "Italiano", "Alemão", "Espanhol", "Árabe", "Tcheco", "Holandês", "Grego", "Japonês", "Coreano", "Polonês", "Português (BR)", "Português (Portugal)", "Russo", "Chinês Simplificado", "Espanhol (América Latina)", "Chinês Tradicional"],
    dubbing: ["Inglês", "Francês", "Italiano", "Alemão", "Espanhol", "Japonês", "Polonês", "Português (BR)", "Português (Portugal)", "Russo", "Chinês Simplificado", "Espanhol (América Latina)"],
    ageRating: "18+",
    links: [{ label: "Steam", url: "https://store.steampowered.com/app/3280350/DEATH_STRANDING_2_ON_THE_BEACH/" }],
    metacriticScore: 89,
    openCriticScore: 90,
    userScore: 8.7,
    siteScores: [
      { site: "IGN", score: 9, url: "https://opencritic.com/game/18226/death-stranding-2-on-the-beach" },
      { site: "GameSpot", score: 7, url: "https://www.gamespot.com/reviews/death-stranding-2-review-tied-up/1900-6418377/" },
      { site: "Eurogamer", score: 8, url: "https://opencritic.com/game/18226/death-stranding-2-on-the-beach" },
      { site: "Push Square", score: 10, url: "https://www.pushsquare.com/reviews/ps5/death-stranding-2-on-the-beach" },
    ],
    worldAvg: 8.5,
    tags: ["exclusivo-sony", "mundo-aberto", "narrativa"],
  },
  {
    id: "10",
    slug: "ghost-of-yotei",
    title: "Ghost of Yōtei",
    cover: "https://media.rawg.io/media/games/30b/30b195c2321d763f807366967ffad793.jpg",
    gallery: [
      "https://media.rawg.io/media/screenshots/910/9109032812e26d6d4715fbde46ec9c3c.jpg",
      "https://media.rawg.io/media/screenshots/dfe/dfefb1a5ad7c0eedf9481609025aece5.jpg",
      "https://media.rawg.io/media/screenshots/864/86425464c5b85b956b3c8819a37e77e4.jpg",
    ],
    description: "Ghost of Yōtei é um jogo de ação e aventura desenvolvido pela Sucker Punch Productions e publicado pela Sony Interactive Entertainment, sequência independente de Ghost of Tsushima.",
    synopsis: "Ambientado no século XVII, 300 anos após os eventos de Ghost of Tsushima, o jogo segue Atsu, uma mercenária solitária atormentada pelo passado, em uma caçada de vingança contra os Seis de Yōtei — responsáveis pela morte de sua família. Sua jornada pelas paisagens inóspitas de Ezo a leva a encontrar aliados inesperados em busca de cura e redenção.",
    developer: "Sucker Punch Productions",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2025-10-02",
    suggestedPrice: 399.90,
    platforms: ["PS5"],
    genres: ["Ação", "Aventura"],
    online: true,
    offline: true,
    maxPlayers: 4,
    languages: ["Alemão", "Chinês Simplificado", "Chinês Tradicional", "Coreano", "Croata", "Dinamarquês", "Espanhol", "Espanhol (México)", "Finlandês", "Francês (França)", "Grego", "Holandês", "Húngaro", "Inglês", "Italiano", "Japonês", "Norueguês", "Polonês", "Português (BR)", "Português (Portugal)", "Russo", "Sueco", "Tailandês", "Tcheco", "Turco", "Árabe"],
    subtitles: ["Alemão", "Chinês Simplificado", "Chinês Tradicional", "Coreano", "Croata", "Dinamarquês", "Espanhol", "Espanhol (México)", "Finlandês", "Francês (França)", "Grego", "Holandês", "Húngaro", "Inglês", "Italiano", "Japonês", "Norueguês", "Polonês", "Português (BR)", "Português (Portugal)", "Russo", "Sueco", "Tailandês", "Tcheco", "Turco", "Árabe"],
    dubbing: ["Alemão", "Espanhol", "Espanhol (México)", "Francês (França)", "Inglês", "Italiano", "Japonês", "Polonês", "Português (BR)", "Português (Portugal)", "Russo"],
    ageRating: "18+",
    links: [{ label: "PS Store", url: "https://store.playstation.com/pt-br/product/UP9000-PPSA26344_00-GHOST2SHIP000000" }],
    metacriticScore: 86,
    openCriticScore: 87,
    userScore: 8.1,
    siteScores: [
      { site: "IGN", score: 8, url: "https://opencritic.com/game/18449/ghost-of-yotei" },
      { site: "GameSpot", score: 9, url: "https://www.gamespot.com/reviews/ghost-of-yotei-review-lone-wolf/1900-6418414/" },
      { site: "Eurogamer", score: 6, url: "https://opencritic.com/game/18449/ghost-of-yotei" },
      { site: "Push Square", score: 9, url: "https://www.pushsquare.com/reviews/ps5/ghost-of-yotei" },
    ],
    worldAvg: 8.0,
    tags: ["exclusivo", "mundo-aberto", "samurai"],
  },
];

export const REVIEWS: Review[] = [
  {
    id: "1",
    gameId: "1",
    title: "God of War Ragnarök — Uma Obra-Prima Épica",
    text: `God of War Ragnarök eleva ainda mais a fasquia estabelecida pelo seu predecessor de 2018. A Santa Monica Studio entregou não apenas uma sequência, mas uma experiência cinematográfica de dar inveja a qualquer produção de Hollywood.

A relação entre Kratos e Atreus continua sendo o coração pulsante do jogo. Vemos o crescimento de Atreus de um adolescente impulsivo para um jovem que começa a entender seu papel no mundo — e a tensão entre pai e filho nunca pareceu tão autêntica e emocionante.

O combate foi ampliado de forma magistral. Além do Leviatã e das Lâminas do Caos, ganhos de novos poderes e habilidades que mantêm as batalhas frescas do início ao fim. Os inimigos são diversificados e desafiadores, exigindo estratégia e adaptação constante.

Os Nove Reinos estão absolutamente deslumbrantes. Cada área tem uma identidade visual própria, e explorar todos eles é uma das maiores alegrias que um jogador pode ter. Svartalfheim, em particular, é uma obra de arte em design de mundo.`,
    pros: [
      "História emocionante e bem escrita",
      "Combate refinado e satisfatório",
      "Mundos deslumbrantes para explorar",
      "Personagens bem desenvolvidos",
      "Trilha sonora épica",
      "Excelente performance no PS5",
    ],
    cons: [
      "Alguns puzzles podem ser repetitivos",
      "O ritmo da história cai levemente no meio",
      "Boss fights nem sempre estão no nível do 2018",
    ],
    conclusion: "God of War Ragnarök é uma das melhores exclusividades do PlayStation e um dos melhores jogos da geração. Imperdível.",
    scores: {
      graphics: 10,
      gameplay: 9.5,
      fun: 10,
      story: 10,
      soundtrack: 9.5,
      performance: 9.5,
      replay: 8.5,
      multiplayer: 0,
      difficulty: 8.5,
      visual: 10,
      ai: 8.5,
      optimization: 9.5,
      content: 9.5,
    },
    overallScore: 9.5,
    author: "Redação Upa que Passa",
    publishedAt: "2022-11-15",
    likes: 342,
  },
  {
    id: "2",
    gameId: "2",
    title: "Marvel's Spider-Man 2 — Dois Heróis, Uma Cidade Maior que Nunca",
    text: `Marvel's Spider-Man 2 não reinventa a fórmula que a Insomniac já vinha refinando desde 2018 — ela a acelera, literalmente. As Web Wings, introduzidas logo nas primeiras horas, transformam o simples ato de atravessar Nova York em algo próximo de um esporte radical: você mergulha de um prédio, abre as asas, pega uma corrente de vento e sai disparado por cima do Hudson sem tocar o chão. É a evolução mais sentida do jogo, e sozinha já justificaria a sequência.

O maior acerto de roteiro é colocar Peter Parker e Miles Morales em rotas emocionais opostas que se cruzam. Peter, cansado e ressentido depois de anos carregando o manto sozinho, encontra em Harry Osborn — recém-curado de uma doença fatal graças ao simbionte — um motivo genuíno para acreditar em segundas chances. Miles, por sua vez, lida com a formatura, a herança do pai e o peso de também ser Homem-Aranha em uma cidade que já tem dois. A dinâmica funciona melhor do que qualquer subtrama vilanesca do jogo, e é o fio que sustenta o terceiro ato.

Só que o roteiro tropeça exatamente onde deveria brilhar: nos vilões. Kraven, o Caçador, chega a Nova York atrás da presa definitiva e domina os primeiros dois terços da campanha com sequências de perseguição tensas — mas raramente compartilha cena com o elenco principal antes de ser eliminado de forma abrupta, deixando a sensação de um arco que terminou cedo demais. Venom, em compensação, é a melhor versão do personagem já vista em um jogo: o simbionte não é só um traje preto, é uma metáfora de vício e solidão que se agarra em Peter e o corrompe aos poucos, culminando em uma das melhores sequências de "queda e redenção" da franquia.

No combate, a Insomniac não reescreve a fórmula estabelecida de contra-ataque e esquiva do primeiro jogo, mas a enche de brinquedos novos. Os tentáculos do simbionte dão a Peter finalizadores brutais e um alcance de área que muda o ritmo das lutas, enquanto Miles continua com seus poderes de bioeletricidade, agora combinados com gadgets exclusivos como o Gume de Prisma. Trocar entre os dois heróis em tempo real, sem tela de carregamento, é um dos maiores trunfos técnicos do jogo — e evita que qualquer um dos dois canse antes da hora.

Visualmente, é o auge da série no PS5. O ray tracing por reflexo nas vitrines de Manhattan, os detalhes de tecido nos trajes (o jogo tem uma quantidade generosa de fatos desbloqueáveis, cada um com efeitos visuais próprios) e a modelagem facial nas cutscenes têm um acabamento de blockbuster. O fast travel, quando necessário, carrega em poucos segundos graças ao SSD — mas a maior parte do tempo você nem vai querer usá-lo, porque balançar pela cidade é bom demais.

O problema é que, fora da espinha dorsal da história, Nova York voltou a ser um mapa cheio de ícones repetidos: bases da Ravencroft, drones para derrubar, projetos de robótica para os alunos de Miles, pedidos repetitivos do aplicativo do Amigão da Vizinhança. É conteúdo que existe para preencher a barra de progresso, não porque tenha algo novo a dizer — e destoa da ambição narrativa do resto do jogo. A campanha principal, por sua vez, é sensivelmente mais curta que a dos jogos anteriores, o que faz esse contraste ficar ainda mais evidente.

Ainda assim, Marvel's Spider-Man 2 entrega o que promete: dois heróis, uma cidade mais viva que nunca e um clímax de simbionte que vale sozinho o preço de entrada. É refinamento em vez de revolução, mas é um refinamento excelente.`,
    pros: [
      "Web swinging redesenhado com as Web Wings torna o deslocamento por Nova York o mais fluido e prazeroso da série",
      "Alternância em tempo real entre Peter e Miles muda o ritmo das missões e evita repetição",
      "Simbionte dá a Peter um kit de combate novo, mais agressivo, com tentáculos e finalizadores brutais",
      "Fast travel quase instantâneo graças ao SSD do PS5 — carregamento em segundos",
      "Arco de Harry Osborn e a relação de Peter com o simbionte são os pontos altos da narrativa",
    ],
    cons: [
      "Kraven ocupa boa parte do tempo de tela mas mal interage com o elenco antes de ser descartado",
      "Atividades paralelas (drones, torres de vigilância, projetos de faculdade) são preenchimento reciclado dos jogos anteriores",
      "Campanha principal é mais curta que a dos títulos passados e o ritmo cai nas seções sem combate, sobretudo com MJ",
      "Poucos supervilões de peso além de Venom e Kraven — muito capanga genérico preenchendo o mapa",
    ],
    conclusion: "Marvel's Spider-Man 2 não reinventa a fórmula da Insomniac, mas a refina com Web Wings viciantes, um duo Peter/Miles bem construído e o melhor Venom já visto em jogos. Falta ambição nas atividades paralelas e nos vilões secundários, mas é fácil recomendar.",
    scores: {
      graphics: 9.5,
      gameplay: 9.0,
      fun: 9.5,
      story: 8.5,
      soundtrack: 8.5,
      performance: 9.0,
      replay: 7.5,
      multiplayer: 0,
      difficulty: 6.5,
      visual: 9.5,
      ai: 7.5,
      optimization: 9.0,
      content: 8.0,
    },
    overallScore: 9.0,
    author: "Theo · Redação UQP",
    publishedAt: "2026-07-02",
    likes: 0,
  },
  {
    id: "3",
    gameId: "4",
    title: "Baldur's Gate 3 — O RPG que Redefine o que 'Suas Escolhas Importam' Significa",
    text: `Existe um momento, em algum ponto das primeiras dez horas de Baldur's Gate 3, em que você percebe que o jogo não vai te punir por tentar algo estúpido — ele vai recompensar. Empurrar um cultista de um penhasco em vez de gastar três turnos de combate. Mentir para um guarda usando uma habilidade de disfarce que você nem sabia que tinha. Simplesmente ignorar uma masmorra inteira porque encontrou outro caminho conversando com a pessoa certa. A Larian Studios não construiu apenas um RPG grande; construiu um RPG que ouve.

A base é Dungeons & Dragons 5ª edição traduzida com uma fidelidade quase obsessiva: rolagens de dado visíveis, vantagem e desvantagem, terreno elevado que muda o resultado de um combate, magias com efeitos colaterais reais no ambiente (incendiar óleo derramado, congelar uma poça para derrubar inimigos). O combate por turnos nunca vira repetição porque cada classe e subclasse joga de um jeito radicalmente diferente — um Druida transformado em urso resolve um encontro de forma completamente distinta de um Ladino furtivo escalando as sombras.

Mas o verdadeiro motor do jogo são os companheiros. Astarion, Shadowheart, Gale, Karlach, Wyll — cada um chega com segredos, uma agenda pessoal e reações próprias ao que você faz. Eles concordam, discordam, se apaixonam, ameaçam ir embora. Não são baús de missão secundária disfarçados de gente: são personagens que julgam suas escolhas com a mesma intensidade que o roteiro principal julga as deles. Uma decisão tomada no Ato 1 — poupar um inimigo, revelar um segredo, escolher um lado em uma disputa tribal — pode reaparecer transformada dezenas de horas depois, no Ato 3, de um jeito que nenhum outro RPG recente consegue igualar.

Visualmente, Baldur's Gate 3 não compete pela vanguarda técnica — não é o jogo mais fotorrealista do catálogo —, mas a direção de arte compensa: os retratos dos personagens em diálogo, as animações de conjuração, os cenários de Sombralânia (Shadow-Cursed Lands) com sua névoa venenosa cravejando ruínas élficas. É um jogo que prioriza legibilidade tática e expressão de personagem acima de espetáculo gráfico, e a escolha funciona.

O grande porém — e é grande mesmo — é a versão de PS5 no Ato 3. A cidade de Baldur's Gate é a área mais densa do jogo, cheia de NPCs, questlines cruzadas e sistemas rodando ao mesmo tempo, e o console visivelmente sofre: o Modo Performance, que deveria manter 60fps, despenca para a faixa dos 20fps em várias regiões, com screen tearing perceptível mesmo no Modo Qualidade. Some a isso relatos consistentes de travamentos e NPCs congelados justamente na reta final da campanha, e fica claro que a otimização de console não acompanhou a ambição do conteúdo — apesar dos patches contínuos da Larian.

Ainda assim, é difícil pensar em outro lançamento recente com essa densidade de conteúdo genuíno: cerca de 17 mil finais diferentes de diálogo (segundo a própria desenvolvedora), múltiplas origens jogáveis, classes que mudam completamente a run e um cooperativo para até quatro jogadores que preserva a reatividade mesmo em grupo — algo que praticamente nenhum RPG cooperativo antes dele conseguiu sustentar sem quebrar a narrativa.

Baldur's Gate 3 é o tipo raro de jogo em que a ambição de design supera qualquer tropeço técnico. Os problemas de performance no Ato 3 do PS5 são reais e frustram, mas não desmontam o que é, disparado, o RPG mais reativo e generoso já lançado nesta geração.`,
    pros: [
      "Reatividade real: NPCs, companheiros e até o mundo lembram e reagem a decisões tomadas dezenas de horas antes",
      "Combate por turnos baseado em D&D 5e recompensa criatividade — empurrar um inimigo de um penhasco é tão válido quanto um feitiço",
      "Companheiros com arcos pessoais entrelaçados à trama principal, não missões paralelas isoladas",
      "Liberdade de resolução de quase toda missão por combate, furtividade, persuasão ou pura trapaça ambiental",
      "Cooperativo para até 4 jogadores com entrada e saída livre, mantendo a reatividade mesmo em grupo",
    ],
    cons: [
      "No PS5, o Ato 3 (cidade de Baldur's Gate) sofre quedas de quadros severas — o Modo Performance pode cair de 60 para a faixa de 20 fps",
      "Bugs de progressão, travamentos e NPCs congelados ficaram mais frequentes justamente na região mais densa do jogo",
      "Câmera isométrica fixa em console exige adaptação para quem vem de RPGs de ação em terceira pessoa",
      "Sistema de regras do D&D 5e tem curva de aprendizado real para quem nunca jogou mesa",
    ],
    conclusion: "Baldur's Gate 3 é o RPG mais reativo e generoso já lançado nesta geração, com companheiros memoráveis e uma liberdade de escolha quase sem precedentes. Os problemas de performance do PS5 no Ato 3 incomodam, mas não chegam perto de ofuscar a grandeza do design.",
    scores: {
      graphics: 8.5,
      gameplay: 9.5,
      fun: 9.5,
      story: 10,
      soundtrack: 9.0,
      performance: 7.5,
      replay: 10,
      multiplayer: 8.5,
      difficulty: 8.0,
      visual: 9.0,
      ai: 8.5,
      optimization: 7.0,
      content: 10,
    },
    overallScore: 9.4,
    author: "Theo · Redação UQP",
    publishedAt: "2026-07-02",
    likes: 0,
  },
  {
    id: "4",
    gameId: "6",
    title: "Alan Wake 2 — Um Pesadelo Escrito com os Pés no Chão e a Cabeça nas Nuvens",
    text: `Alan Wake 2 abre uma ferida que o jogo original deixou em aberto há treze anos e a aprofunda com uma coragem estrutural rara: em vez de contar uma história, conta duas ao mesmo tempo, e faz as duas dialogarem entre si como se fossem reflexos distorcidos uma da outra. De um lado, a agente Saga Anderson chega a Bright Falls para investigar assassinatos rituais que parecem citar diretamente a ficção de um escritor desaparecido. Do outro, o próprio Alan Wake segue preso na Dark Place, reescrevendo compulsivamente sua própria história de terror numa tentativa de escapar dela.

A Mind Place de Saga é a melhor ideia de design do jogo. É um escritório mental que ela pode acessar a qualquer momento — um quadro de evidências físico, com fotos, post-its e barbante vermelho conectando pistas, onde o jogador literalmente monta o caso como um detetive faria numa parede de conspiração. Não é só estética: é a ferramenta que transforma investigação em mecânica jogável, e faz cada capítulo de Saga parecer avançar uma lógica própria, quase policial, em contraste com o pesadelo fragmentado de Alan.

E é aí que o jogo se torna, sem exagero, um dos experimentos mais ousados de terror audiovisual já feitos. A sequência musical "Herald of Darkness", em que Alan literalmente entra em um musical dentro de sua própria mente perturbada, é o tipo de cena que resume por que a Remedy tem carta branca criativa: é estranha, é linda, é assustadora, e funciona porque o jogo já passou horas construindo a lógica interna de que a ficção de Alan sangra para a realidade.

Visualmente, é difícil apontar um jogo de terror mais ambicioso tecnicamente. A Remedy mistura sequências em live-action, cutscenes em FMV com atores reais projetados sobre cenários digitais, e renderização em tempo real de dar inveja — a transição entre a Bright Falls ensolarada e fria de Saga e a Dark Place decadente e claustrofóbica de Alan cria a sensação de duas realidades colidindo, não só duas paletas de cor diferentes.

O combate, no entanto, não acompanha essa ambição. É funcional — apontar a lanterna para queimar a proteção sombria do Taken antes de atirar continua satisfatório nos primeiros encontros —, mas o arsenal cresce pouco, os tipos de inimigo se repetem e a variedade tática estagna bem antes do final. É um jogo de sobrevivência que prioriza tensão de recursos (munição escassa, poucos itens de cura) acima de profundidade de combate, e isso é uma escolha de design defensável, mas ainda assim deixa a sensação de que a Remedy investiu toda a criatividade na narrativa e deixou o gameplay em segundo plano.

No PS5, o Modo Performance sofre com engasgos e screen tearing em cenas mais carregadas, principalmente nas passagens da Dark Place com mais efeitos de partícula e distorção visual simultâneos — o preço de rodar um dos motores gráficos mais exigentes da geração em hardware de console. E o ritmo, especialmente no primeiro terço do jogo, testa a paciência: os capítulos de puzzle de Alan interrompem justamente os momentos em que a tensão deveria estar subindo, e a conexão entre as duas tramas demora a ficar clara o suficiente para justificar a alternância constante.

Ainda assim, poucos jogos de terror recentes arriscam tanto quanto Alan Wake 2 — e a maioria dos riscos compensa. É uma experiência que se lê mais como literatura interativa do que como jogo de ação, e quem topar entrar nessa lógica encontra um dos pesadelos mais bem escritos e mais visualmente memoráveis do gênero.`,
    pros: [
      "Duas campanhas entrelaçadas (Saga em Bright Falls, Alan na Dark Place) que se comentam e se completam sem nunca confundir o jogador",
      "Mind Place de Saga transforma investigação policial em um quebra-cabeça físico de quadro de evidências, com red string e tudo",
      "Sequência musical 'Herald of Darkness' é um dos momentos mais ousados e memoráveis de terror já feitos em jogo",
      "Direção de arte mistura live-action, FMV e renderização em tempo real sem que a costura apareça",
      "Trilha sonora e design de som constroem tensão sem depender só de jump scares",
    ],
    cons: [
      "Combate é funcional mas raso perto da ambição da narrativa — poucas armas, poucos tipos de Taken, pouca evolução ao longo do jogo",
      "Modo Performance no PS5 tem quedas de quadro e screen tearing perceptíveis em cenas mais carregadas",
      "Seções de puzzle nas sequências de Alan quebram o ritmo justamente quando a tensão deveria crescer",
      "Início lento — o jogo demora a deixar claro por que vale a pena acompanhar as duas histórias em paralelo",
    ],
    conclusion: "Alan Wake 2 é um dos experimentos narrativos mais corajosos do terror em jogos, sustentado por uma direção de arte e trilha sonora extraordinárias. O combate raso e as quedas de performance no PS5 são as únicas manchas em uma experiência que se lê quase como literatura interativa.",
    scores: {
      graphics: 9.5,
      gameplay: 7.5,
      fun: 8.0,
      story: 9.5,
      soundtrack: 9.5,
      performance: 7.5,
      replay: 6.5,
      multiplayer: 0,
      difficulty: 6.0,
      visual: 9.5,
      ai: 6.5,
      optimization: 7.0,
      content: 8.0,
    },
    overallScore: 9.0,
    author: "Theo · Redação UQP",
    publishedAt: "2026-07-02",
    likes: 0,
  },
];

export const USERS: User[] = [
  {
    id: "1",
    nickname: "KratosFan_BR",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=KratosFan",
    bio: "Gamer de carteirinha. Platinador compulsivo.",
    favoriteGames: ["1", "2", "4"],
    console: "PS5",
    city: "São Paulo",
    state: "SP",
    socialLinks: [
      { platform: "twitch", url: "#" },
      { platform: "youtube", url: "#" },
    ],
    reviewsCount: 47,
    commentsCount: 284,
    tradesCount: 23,
    reputation: 98,
    level: 42,
    achievements: [
      { id: "1", name: "Platinador", description: "Conquistou 10 platinas", icon: "🏆" },
      { id: "2", name: "Crítico", description: "Escreveu 50 reviews", icon: "✍️" },
      { id: "3", name: "Negociante", description: "Realizou 20 trocas", icon: "🤝" },
    ],
    joinedAt: "2021-03-15",
  },
  {
    id: "2",
    nickname: "SpiderMilena",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SpiderMilena",
    bio: "Fã da Marvel e de JRPGs. Sempre procurando o próximo platinão.",
    favoriteGames: ["2", "3"],
    console: "PS5",
    city: "Rio de Janeiro",
    state: "RJ",
    socialLinks: [],
    reviewsCount: 12,
    commentsCount: 89,
    tradesCount: 7,
    reputation: 94,
    level: 18,
    achievements: [
      { id: "1", name: "Iniciante", description: "Fez seu primeiro review", icon: "⭐" },
    ],
    joinedAt: "2023-06-20",
  },
];

export const LISTINGS: Listing[] = [
  {
    id: "1",
    userId: "1",
    userNickname: "KratosFan_BR",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=KratosFan",
    userReputation: 98,
    photos: ["https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png"],
    title: "God of War Ragnarök - Lacrado",
    description: "Jogo lacrado, comprado na pré-venda, nunca aberto. Migrei para o digital.",
    price: 199.90,
    condition: "lacrado",
    media: "fisica",
    city: "São Paulo",
    state: "SP",
    shipping: true,
    pickup: true,
    acceptsTrade: true,
    paymentMethods: ["pix", "dinheiro"],
    category: "Ação",
    gameId: "1",
    createdAt: "2024-01-15",
    views: 234,
    favorites: 18,
    active: true,
    wantedGames: ["Spider-Man 2", "Baldur's Gate 3"],
  },
  {
    id: "2",
    userId: "2",
    userNickname: "SpiderMilena",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SpiderMilena",
    userReputation: 94,
    photos: ["https://upload.wikimedia.org/wikipedia/en/0/0f/SpiderMan2PS5BoxArt.jpeg"],
    title: "Spider-Man 2 - Usado - Bom Estado",
    description: "Jogo em bom estado, poucas arranhadas na capa. Zerado, todos os troféus coletados.",
    price: 159.90,
    condition: "bom estado",
    media: "fisica",
    city: "Rio de Janeiro",
    state: "RJ",
    shipping: true,
    pickup: false,
    acceptsTrade: false,
    paymentMethods: ["pix", "cartao"],
    category: "Ação",
    gameId: "2",
    createdAt: "2024-01-20",
    views: 145,
    favorites: 9,
    active: true,
  },
  {
    id: "3",
    userId: "1",
    userNickname: "KratosFan_BR",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=KratosFan",
    userReputation: 98,
    photos: ["https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_600x900.jpg"],
    title: "Baldur's Gate 3 - Troca!",
    description: "Tenho BG3 e procuro trocar por Final Fantasy XVI + diferença. Jogo em ótimo estado.",
    price: 280.00,
    condition: "como novo",
    media: "fisica",
    city: "São Paulo",
    state: "SP",
    shipping: true,
    pickup: true,
    acceptsTrade: true,
    paymentMethods: ["pix"],
    category: "RPG",
    gameId: "4",
    createdAt: "2024-01-25",
    views: 89,
    favorites: 4,
    active: true,
    wantedGames: ["Final Fantasy XVI"],
  },
];

export const NEWS: NewsArticle[] = [
  {
    id: "1",
    slug: "ps5-pro-lancamento-brasil",
    title: "PS5 Pro chega ao Brasil com preço oficial de R$ 4.999",
    excerpt: "Sony anuncia o PS5 Pro para o mercado brasileiro com GPU aprimorada e suporte a 8K.",
    content: "A Sony Interactive Entertainment anunciou oficialmente o PlayStation 5 Pro para o mercado brasileiro...",
    cover: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Video_%C3%BCber_die_PS5_Pro_%28BeatEmUps%29_%282160p_60fps_VP9-128kbit_AAC%29-00.02.23.200.png",
    author: "Redação UQP",
    publishedAt: "2024-09-10",
    category: "Hardware",
    tags: ["PS5", "PS5 Pro", "Sony", "Hardware"],
    views: 12450,
    likes: 342,
  },
  {
    id: "2",
    slug: "gta-6-data-lancamento-confirmada",
    title: "GTA 6: Data de lançamento no PS5 confirmada para 2025",
    excerpt: "Rockstar Games confirma que GTA VI chegará em maio de 2025 para PlayStation 5 e Xbox Series.",
    content: "A Rockstar Games confirmou que Grand Theft Auto VI terá lançamento em maio de 2025...",
    cover: "https://upload.wikimedia.org/wikipedia/en/4/46/Grand_Theft_Auto_VI.png",
    author: "Redação UQP",
    publishedAt: "2024-01-08",
    category: "Notícias",
    tags: ["GTA 6", "Rockstar", "PS5", "Lançamento"],
    views: 45200,
    likes: 1203,
  },
  {
    id: "3",
    slug: "state-of-play-resumo",
    title: "State of Play: Todos os anúncios do evento da Sony",
    excerpt: "Confira todos os jogos e novidades anunciadas no State of Play de Janeiro de 2024.",
    content: "O State of Play de Janeiro trouxe diversas novidades para os donos de PlayStation 5...",
    cover: "https://upload.wikimedia.org/wikipedia/commons/7/77/Black_and_white_Playstation_5_base_edition_with_controller.png",
    author: "Redação UQP",
    publishedAt: "2024-01-31",
    category: "Eventos",
    tags: ["State of Play", "Sony", "PS5", "Anúncios"],
    views: 23100,
    likes: 678,
  },
  {
    id: "4",
    slug: "sony-fim-producao-midia-fisica-ps5-2028",
    title: "Sony vai encerrar a produção de mídias físicas para novos jogos de PlayStation em 2028",
    excerpt: "A partir de janeiro de 2028, novos jogos lançados para os consoles PlayStation, incluindo o PS5, serão distribuídos apenas em formato digital.",
    content: "A Sony Interactive Entertainment anunciou nesta quarta-feira (1º) que vai encerrar a produção de mídias físicas para todos os novos jogos lançados nos consoles PlayStation, incluindo o PS5, a partir de janeiro de 2028. O comunicado foi publicado por Sid Shuman, Senior Director de Comunicações de Conteúdo da SIE, no PlayStation Blog oficial, tanto na versão em inglês quanto na brasileira.\n\nSegundo o texto, \"novos jogos serão lançados na PlayStation Store e em revendedores parceiros apenas em formato digital\" a partir da data de corte. A companhia atribui a decisão à mudança nas preferências dos consumidores, que têm optado cada vez mais por comprar jogos digitalmente em vez de em disco físico — uma tendência que vem se consolidando há anos na indústria.\n\nÉ importante notar o que a mudança não afeta: segundo o próprio comunicado, \"essa transição não afeta jogos que já foram lançados, ou que serão lançados, em formato de disco antes de janeiro de 2028\". Ou seja, coleções físicas existentes e lançamentos programados até o fim de 2027 seguem normalmente, e os jogos comprados digitalmente continuam disponíveis para download mesmo depois da mudança — algo reforçado por outro comunicado da mesma semana sobre o fechamento futuro da PlayStation Store para PS3 e PS Vita.\n\nA repercussão na imprensa internacional foi rápida. O site especializado Push Square noticiou o anúncio e registrou que a Sony chegou a suspender temporariamente sua atividade em redes sociais nas horas seguintes, em meio à reação negativa de parte da comunidade — inclusive desenvolvedores independentes que dependem de vendas físicas em mercados com acesso limitado à internet de banda larga. Para o público brasileiro, a notícia acende um alerta sobre o futuro das lojas físicas de jogos e do mercado de usados, hoje fortemente dependente de mídia em disco para consoles PlayStation.",
    cover: "https://blog.br.playstation.com/tachyon/sites/4/2026/07/64de1a59e07f3731c6e0ca0dd8da7ecde5e2aef0.jpg",
    author: "Kai · Repórter UQP",
    publishedAt: "2026-07-02",
    category: "Hardware",
    tags: ["PS5", "Sony", "mídia física", "PlayStation Store", "indústria"],
    views: 0,
    likes: 0,
  },
  {
    id: "5",
    slug: "playstation-plus-jogos-julho-2026",
    title: "PlayStation Plus revela jogos mensais de julho: Call of Duty: Modern Warfare III, For the King II e CrossCode",
    excerpt: "Assinantes do PlayStation Plus terão acesso a três novos jogos entre 7 de julho e 3 de agosto, incluindo o FPS Call of Duty: Modern Warfare III.",
    content: "A Sony revelou nesta quarta-feira (1º) os jogos mensais do PlayStation Plus para julho de 2026, disponíveis para assinantes entre os dias 7 de julho e 3 de agosto. A seleção deste mês mistura ação em primeira pessoa, RPG cooperativo e aventura retrô, com títulos compatíveis com PS5 e PS4.\n\nO destaque da leva é Call of Duty: Modern Warfare III, que chega ao catálogo com sua campanha (continuação direta de Modern Warfare II), 16 mapas multiplayer remasterizados e o modo mundo aberto de zumbis, jogável em cooperação com outros jogadores. É o título mais robusto da seleção e deve atrair o maior volume de downloads entre os assinantes brasileiros.\n\nCompletam a lista For the King II, RPG cooperativo com elementos de roguelike e estética inspirada em jogos de tabuleiro, jogável sozinho ou com até quatro jogadores no mundo de Fahrul, e CrossCode, RPG de ação em 2D com visual retrô de 16 bits que combina quebra-cabeças, combate ágil e uma narrativa de ficção científica com sistemas de equipamento e habilidades.\n\nOs três jogos ficam disponíveis para resgate a partir da próxima segunda-feira (7) e permanecem no catálogo de assinantes até o início de agosto, quando a Sony deve anunciar a leva seguinte.",
    cover: "https://blog.br.playstation.com/tachyon/sites/4/2026/07/8240f0a279acaeaa962be1a5d2398959ddbdfb47-scaled.jpg",
    author: "Kai · Repórter UQP",
    publishedAt: "2026-07-02",
    category: "Notícias",
    tags: ["PS5", "PlayStation Plus", "Call of Duty", "CrossCode", "For the King II"],
    views: 0,
    likes: 0,
  },
  {
    id: "6",
    slug: "dune-awakening-chega-ps5-setembro",
    title: "Dune: Awakening ganha data de lançamento no PS5: 22 de setembro, com modo single-player inédito",
    excerpt: "O survival de mundo aberto ambientado em Arrakis chega ao PS5 em 22 de setembro com um modo solo criado especialmente para a versão de console.",
    content: "A Funcom e a Sony confirmaram nesta quinta-feira (2) que Dune: Awakening, o survival de mundo aberto ambientado no planeta Arrakis, chega ao PlayStation 5 em 22 de setembro de 2026. O anúncio foi feito em post assinado por Erling Ellingsen, diretor de marketing da Funcom, no PlayStation Blog oficial, e confirmado também na versão em espanhol do blog com a mesma data.\n\nA grande novidade para quem joga no console é o modo single-player, inexistente na versão de PC, onde o jogo é exclusivamente multiplayer. Segundo a publicadora, \"fazer um jogo inerentemente multiplayer funcionar totalmente em modo solo não foi uma tarefa fácil\": o sistema simula a disputa de outros jogadores pelos objetivos do Landsraad e oferece amplas opções de personalização de dificuldade, incluindo a possibilidade de desativar por completo os vermes-de-areia. Quem preferir jogar com amigos também pode alugar um servidor privado.\n\nNo quesito performance, o PS5 padrão vai rodar o jogo em modo Performance a 60fps com frame generation, ou em modo Qualidade a 30fps, ambos com upscaling para 4K. No PS5 Pro, o modo Performance entrega 60fps nativos, sem depender de frame generation, também em 4K upscalado.\n\nA versão física do jogo será distribuída pela Bandai Namco Entertainment Europe na Europa, Austrália e Nova Zelândia, e pela Solutions 2 Go nas Américas — incluindo o Brasil. O lançamento no Japão está previsto para outubro, com editora local ainda a ser anunciada. Dune: Awakening entra assim na lista de lançamentos aguardados do segundo semestre no PS5, num momento em que a própria Sony está no centro do debate sobre o futuro da mídia física no console.",
    cover: "https://blog.playstation.com/tachyon/2028/07/dd2f042a3df051c1f977a45b4accc8407e72e2c5.jpg",
    author: "Kai · Repórter UQP",
    publishedAt: "2026-07-02",
    category: "Lançamentos",
    tags: ["PS5", "Dune Awakening", "Funcom", "Bandai Namco", "survival"],
    views: 0,
    likes: 0,
  },
];

export function getScoreColor(score: number): string {
  if (score >= 9) return "text-green-400";
  if (score >= 7.5) return "text-lime-400";
  if (score >= 6) return "text-yellow-400";
  if (score >= 4) return "text-orange-400";
  return "text-red-400";
}

export function getScoreBg(score: number): string {
  if (score >= 9) return "bg-green-400";
  if (score >= 7.5) return "bg-lime-400";
  if (score >= 6) return "bg-yellow-400";
  if (score >= 4) return "bg-orange-400";
  return "bg-red-400";
}

export function formatScore(score: number): string {
  return score % 1 === 0 ? score.toString() : score.toFixed(1);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(price);
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("pt-BR");
}
